SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE participation;
ALTER TABLE truck AUTO_INCREMENT = 1;

TRUNCATE TABLE truck;
ALTER TABLE truck AUTO_INCREMENT = 1;

TRUNCATE TABLE schedule;
ALTER TABLE account AUTO_INCREMENT = 1;

TRUNCATE TABLE event;
ALTER TABLE account AUTO_INCREMENT = 1;

TRUNCATE TABLE account;
ALTER TABLE account AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;
