spring:
  profiles:
    active: local
  # jpa
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

# log config
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}:%-4relative] %green([%thread]) [traceId=%X{traceId}] %highlight(%-5level) [%C.%M:%line] - %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss}:%-4relative] [%thread] [traceId=%X{traceId}] %-5level [%C.%M:%line] - %msg%n"
