server:
  shutdown: graceful

spring:
  profiles:
    active: local
  # jpa
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false # OSIV off
  # async thread pool
  task:
    execution:
      pool:
        core-size: 8
        keep-alive: 60s # idle time before thread termination
      shutdown:
        await-termination: true
        await-termination-period: 60s
      thread-name-prefix: async-push-sender-

# log config
logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}:%-4relative] %green([%thread]) [traceId=%X{traceId}] %highlight(%-5level) [%C.%M:%line] - %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss}:%-4relative] [%thread] [traceId=%X{traceId}] %-5level [%C.%M:%line] - %msg%n"

# disable swagger default url
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
  cache.disabled: true
