spring:
# h2 in-memory db
  h2:
    console:
      enabled: true
      path: /h2-console
# database source
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
