spring:
  # h2 in-memory db
  h2:
    console:
      enabled: true
      path: /h2-console
  # database source
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  # flyway
  flyway:
    locations: [ classpath:db/migration, classpath:db/data ] # initialize default data

logging:
  level:
    # enable hibernate sql parameter log
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: TRACE

connectruck:
  # CORS
  cors:
    allowed-origin: http://localhost:3000
