spring:
# h2 in-memory db
  h2:
    console:
      enabled: true
      path: /h2-console
# database source
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
# jpa
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create # ddl-auto
