name: Test spring boot app on PR
on:
  pull_request:
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'backend/**'

# Test Result Publish를 위한 permissions
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_TOKEN }}
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./backend/foodtruck/gradlew

      - name: Test with Gradle
        working-directory: ./backend/foodtruck
        run: ./gradlew --info test

        # Test 후 Report 생성
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: '**/build/test-results/test/TEST-*.xml'
